### ISSUE TITLE
Actualizar portada del Documento Metodológico

### ISSUE THREAD

**Issue by pablotis** [d4t4tur/evyth_metodologia#3]

**Comment by pablotis** [comment]
@hernancolazo este también!

![imagen](https://user-images.githubusercontent.com/30708601/172226305-d8f654a6-e711-4f5f-aefb-96a76ed7495b.png)

**Comment by hernancolazo** [comment]
Alguno me puede ayudar a encontrar la ruta para ver donde esta guardada la portada anterior, no la encuentro.

**Comment by hernancolazo** [comment]
[portadadt1.pdf](https://github.com/d4t4tur/evyth_metodologia/files/8856012/portadadt1.pdf)
por el momento no encuentro la ruta para cambiar la portada. la dejo por acá para que no se pierda.
